name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🐛 Fixes'
    labels: ['bug', 'fix']
  - title: '🧰 Maintenance'
    labels: ['chore', 'deps', 'maintenance']
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  ## Changes

  $CHANGES

  ## Artifacts
  - Linux x86_64 (musl): `codex-x86_64-unknown-linux-musl`
