name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  linux:
    name: Linux ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            use_cross: false
          - target: x86_64-unknown-linux-musl
            use_cross: false
          - target: aarch64-unknown-linux-musl
            use_cross: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            vendor/codex/codex-rs

      - name: Install dependencies
        if: matrix.use_cross == false
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config curl git make
          if [[ "${{ matrix.target }}" == *"musl"* ]]; then
            sudo apt-get install -y musl-tools
          fi

      - name: Install cross
        if: matrix.use_cross == true
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Build (cargo)
        if: matrix.use_cross == false
        working-directory: vendor/codex/codex-rs
        run: |
          cargo build -p codex-cli --release --target ${{ matrix.target }}

      - name: Build (cross)
        if: matrix.use_cross == true
        working-directory: vendor/codex/codex-rs
        run: |
          cross build -p codex-cli --release --target ${{ matrix.target }}

      - name: Package
        run: |
          mkdir -p dist
          BIN=vendor/codex/codex-rs/target/${{ matrix.target }}/release/codex
          NAME=codex-${{ matrix.target }}
          cp "$BIN" "dist/$NAME"
          (cd dist && sha256sum "$NAME" >> SHA256SUMS.txt)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.target }}
          path: |
            dist/codex-${{ matrix.target }}
            dist/SHA256SUMS.txt

  macos:
    name: macOS ${{ matrix.runner }} (${{ matrix.target }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-13
            target: x86_64-apple-darwin
          - runner: macos-14
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            vendor/codex/codex-rs
      - name: Build
        working-directory: vendor/codex/codex-rs
        run: cargo build -p codex-cli --release --target ${{ matrix.target }}
      - name: Package
        run: |
          mkdir -p dist
          BIN=vendor/codex/codex-rs/target/${{ matrix.target }}/release/codex
          NAME=codex-${{ matrix.target }}
          cp "$BIN" "dist/$NAME"
          (cd dist && shasum -a 256 "$NAME" >> SHA256SUMS.txt)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.target }}
          path: |
            dist/codex-${{ matrix.target }}
            dist/SHA256SUMS.txt

  windows:
    name: Windows x86_64-msvc
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            vendor/codex/codex-rs
      - name: Build
        working-directory: vendor/codex/codex-rs
        run: cargo build -p codex-cli --release --target x86_64-pc-windows-msvc
      - name: Package
        shell: bash
        run: |
          mkdir -p dist
          BIN=vendor/codex/codex-rs/target/x86_64-pc-windows-msvc/release/codex.exe
          NAME=codex-x86_64-pc-windows-msvc.exe
          cp "$BIN" "dist/$NAME"
          (cd dist && sha256sum "$NAME" >> SHA256SUMS.txt)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-x86_64
          path: |
            dist/codex-x86_64-pc-windows-msvc.exe
            dist/SHA256SUMS.txt

  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: [linux, macos, windows]
    steps:
      - uses: actions/download-artifact@v5
        with:
          path: artifacts
      - name: Aggregate
        run: |
          mkdir -p dist
          find artifacts -type f -name 'codex-*' -exec cp {} dist/ \;
          # Merge checksums
          cat artifacts/*/SHA256SUMS.txt >> dist/SHA256SUMS.txt || true
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
