name: Social Preview

on:
  push:
    branches: [ main ]
    paths:
      - assets/og.svg
      - .github/workflows/social-preview.yml
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install rsvg and ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y librsvg2-bin imagemagick
      - name: Render PNG from SVG
        run: |
          mkdir -p .work
          rsvg-convert -w 1280 -h 640 assets/og.svg -o .work/og.png
          ls -lh .work/og.png
      - name: Upload as repository social preview
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          OWNER=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f1)
          REPO=$(echo "$GITHUB_REPOSITORY" | cut -d/ -f2)
          curl -sS -X PUT \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: image/png" \
            --data-binary @.work/og.png \
            "https://api.github.com/repos/$OWNER/$REPO/social_preview" \
            >/dev/null
      - name: Commit PNG copy (optional cache)
        run: |
          if [ ! -f assets/og.png ] || ! cmp -s .work/og.png assets/og.png; then
            cp .work/og.png assets/og.png
            git config user.name 'github-actions'
            git config user.email 'github-actions@users.noreply.github.com'
            git add assets/og.png
            git commit -m 'brand: update social preview og.png [skip ci]' || true
            git push || true
          fi

